# Generated by Django 2.2 on 2020-01-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatemodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
